jobs:
# Replace params / app_name with your heroku app name
- name: ci
  plan:
  - aggregate:
    - get: devops-exam-app
      trigger: true
    - get: devops-exam-infra
  - task: sync_heroku
    file: devops-exam-infra/concourse/heroku/heroku_sync.yml
    input_mapping: {source: devops-exam-app}
    params:
      app_name: ((heroku_app_name))
      heroku_email: ((heroku_email))
      heroku_api_token: ((heroku_api_key))

- name: infra
  plan:
  - aggregate:
    - get: devops-exam-infra
      trigger: true
  - task: apply
    file: devops-exam-infra/concourse/terraform/task.yml
    input_mapping: {source: devops-exam-infra}
    params:
      github_token: ((github_token))
      heroku_api_key: ((heroku_api_key))
      command: apply
      directories: |
          terraform

#  The with-state is an output from the apply task. It's a git repo with
#  An updated terraform tfstate file.
  - put: devops-exam-infra
    params:
      repository: with-state
      rebase: true

resources:
- name: devops-exam-app
  type: git
  source:
      uri: git@github.com:GardOS/devops-exam-app.git
      branch: master
      private_key: ((deploy_key_app))
- name: devops-exam-infra
  type: git
  source:
      uri: git@github.com:GardOS/devops-exam-infra.git
      branch: master
      private_key: ((deploy_key_infra))
