jobs:
  - name: infra
    plan:
      - aggregate:
          - get: devops-exam-infra
      - task: apply
        file: devops-exam-infra/concourse/terraform/terraform.yml
        input_mapping: { source: devops-exam-infra }
        params:
          github_token: ((github_token))
          heroku_api_key: ((heroku_api_key))	
          statuscake_api_key: ((statuscake_api_key))
          command: apply
          directories: |
            terraform
      - put: devops-exam-infra
        params:
          repository: with-state
          rebase: true
  - name: build
    plan:
      - aggregate:
          - get: devops-exam-app
            trigger: true
          - get: devops-exam-infra
      - task: mvn-build
        file: devops-exam-infra/concourse/java/java.yml
        input_mapping: { source: devops-exam-app }
      - put: docker-image-app
        params:
          build: app
  - name: deploy
    plan:
      - aggregate:
        - get: devops-exam-infra
        - get: docker-image-app
          trigger: true
          passed: [build]
      - task: deploy-container
        file: devops-exam-infra/concourse/heroku/deploy-container.yml
        params:
          app_name: ((heroku_app_name))-ci
          heroku_email: ((heroku_email))	
          heroku_api_key: ((heroku_api_key))

resources:
  - name: devops-exam-app
    type: git
    source:
      uri: git@github.com:((github_username))/devops-exam-app.git
      branch: master
      private_key: ((deploy_key_app))
  - name: devops-exam-infra
    type: git
    source:
      uri: git@github.com:((github_username))/devops-exam-infra.git
      branch: master
      private_key: ((deploy_key_infra))
  - name: docker-image-app
    type: docker-image
    source:
      repository: registry.heroku.com/((heroku_app_name))-ci/web
      username: ((heroku_email))
      password: ((heroku_api_key))
