jobs:
  - name: deploy-app
    plan:
      - aggregate:
          - get: devops-exam-app
          - get: devops-exam-infra
      - task: mvn_build
        file: devops-exam-infra/concourse/java/task.yml
        input_mapping: { source: devops-exam-app }

      - task: push_to_heroku
        file: devops-exam-infra/concourse/heroku/push_master_to_heroku.yml
        input_mapping: { source: devops-exam-app }
        params:
          app_name: ((heroku_app_name))
          heroku_email: ((heroku_email))
          heroku_api_key: ((heroku_api_key))

- name: infra
  plan:
  - aggregate:
    - get: devops-exam-infra
  - task: apply
    file: devops-exam-infra/concourse/terraform/task.yml
    input_mapping: {source: devops-exam-infra}
    params:
      github_token: ((github_token))
      heroku_api_key: ((heroku_api_key))
      statuscake_api_key: ((statuscake_api_key))
      command: apply
      directories: |
          terraform
  - put: devops-exam-infra
    params:
      repository: with-state
      rebase: true

resources:
  - name: devops-exam-app
    type: git
    source:
      uri: git@github.com:GardOS/devops-exam-app.git
      branch: master
      private_key: ((deploy_key_app))
  - name: devops-exam-infra
    type: git
    source:
      uri: git@github.com:GardOS/devops-exam-infra.git
      branch: master
      private_key: ((deploy_key_infra))
